### PR TITLE
modified panel

### PR DESCRIPTION
**Pull request by ghost**
image

### CODE REVIEW

**Comment by adarshsanjeev** [comment]
This doesn't seem to be working for me, are you sure you pushed all the changes?
selection_006

**Comment by ghost** [comment]
Does this work?
https://researchweb.iiit.ac.in/~anukul.sangwan/parallax/

**Comment by adarshsanjeev** [comment]
Nope, it only seems to work on your monitor's dimensions, just test it on some other laptops too and make the changes.

**Comment by ghost** [comment]
I tested this on chrome on multiple laptops, looked fine.
But the original panel appears differently on chrome and firefox, so I'm not sure how to go further.

image

image

**Comment by adarshsanjeev** [comment]
It seems that firefox resizes the box according to the text inside, so it should look okay after the content is filled in. Good work.

**Pull request merged**
