### PR TITLE
modified panel - 2

### PR DESCRIPTION
**Pull request by ghost**
I've tried a different approach which makes the changes from https://github.com/mukulhase/felicity16-website/pull/13 work on both chrome and firefox.

A working copy is on https://researchweb.iiit.ac.in/~anukul.sangwan/parallax/

### CODE REVIEW

**Comment by adarshsanjeev** [comment]
Works. Nice.

**Comment by vikasTmz** [comment]
Hey can you also make all the links at a higher z-index. Don't do this for a container or panel but for links like Login or Register after they are visible. Or change the panel's z-index when opened. 
Open **parallax-particle.html** and you can see the links aren't click-able since the particles overlap.

**Comment by adarshsanjeev** [comment]
I'm doing that already

**Comment by adarshsanjeev** [comment]
I'm already working on that

**Pull request merged**
